# launcher name & url
launcher_name=FuryMCLauncher
launcher_app_name=FuryMC Launcher
launcher_short_name=FMC
url_home=https://github.com/FuryMCLauncher/FuryMCLauncher

# your OAuth client id
#oauth_client_id=xxx

# your CurseForge API key
#curseforge_api_key=xxx

# default key, please add it yourself.
#default_store_password=xxx
#default_key_password=xxx

# launcher version
launcher_version_code=5
launcher_version_name=0.0.5